name: .NET CI/CD

on:
  push:
    branches: [ qa ]
  pull_request: 
    branches: [ qa ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Environment=QA

    - name: Publish
      run: dotnet publish --no-restore --output ./publish/ --configuration Release /p:Environment=QA

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: contafacil.tech
        username: ${{ secrets.FTP_USERNAME_QA }}
        password: ${{ secrets.FTP_PASSWORD_QA }}
        local-dir: ./publish/
        dangerous-clean-slate: true
